CREATE SCHEMA IF NOT EXISTS exchange;

CREATE TABLE exchange.client (
    id_client integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom varchar(50) NOT NULL,
    prenom varchar(50) NOT NULL,
    telephone varchar(20),
    email varchar(100) NOT NULL UNIQUE
);

CREATE TABLE exchange.adresse (
    id_adresse integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_rue varchar(10),
    rue varchar(100),
    ville varchar(50),
    code_postal varchar(20),
    pays varchar(50),
    id_client integer NOT NULL UNIQUE
);

CREATE TABLE exchange.compte_client (
    id_compte integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_creation date NOT NULL DEFAULT CURRENT_DATE,
    statut varchar(20) NOT NULL,
    id_client integer NOT NULL UNIQUE
);

CREATE TABLE exchange.devise (
    id_devise integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_devise char(3) NOT NULL UNIQUE,
    nom_devise varchar(50) NOT NULL,
    symbole varchar(10)
);

CREATE TABLE exchange.taux_change (
    id_taux integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valeur_taux numeric(12,6) NOT NULL,
    date_mise_a_jour timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_devise_source integer NOT NULL,
    id_devise_cible integer NOT NULL,
    CONSTRAINT chk_devise_diff CHECK (id_devise_source <> id_devise_cible),
    CONSTRAINT chk_taux_positive CHECK (valeur_taux > 0)
);

CREATE TABLE exchange.transaction (
    id_transaction integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_transaction timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    montant_initial numeric(12,2) NOT NULL,
    montant_converti numeric(12,2) NOT NULL,
    statut varchar(30) NOT NULL,
    id_client integer NOT NULL,
    id_devise_source integer NOT NULL,
    id_devise_cible integer NOT NULL,
    id_taux integer NOT NULL,
    CONSTRAINT chk_montants_positive CHECK (montant_initial > 0 AND montant_converti > 0)
);

CREATE TABLE exchange.mode_paiement (
    id_mode_paiement integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_mode varchar(50) NOT NULL UNIQUE
);

CREATE TABLE exchange.prestataire_paiement (
    id_prestataire integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_prestataire varchar(100) NOT NULL UNIQUE,
    type_service varchar(50)
);

CREATE TABLE exchange.paiement (
    id_paiement integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_paiement timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    montant_paye numeric(12,2) NOT NULL,
    id_transaction integer NOT NULL UNIQUE,
    id_mode_paiement integer NOT NULL,
    id_prestataire integer NOT NULL,
    CONSTRAINT chk_montant_paye CHECK (montant_paye > 0)
);

CREATE TABLE exchange.historique_transaction (
    id_historique integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_action timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    action varchar(100) NOT NULL,
    id_transaction integer NOT NULL
);

ALTER TABLE exchange.adresse
    ADD CONSTRAINT fk_adresse_client
    FOREIGN KEY (id_client) REFERENCES exchange.client(id_client) ON DELETE CASCADE;

ALTER TABLE exchange.compte_client
    ADD CONSTRAINT fk_compte_client
    FOREIGN KEY (id_client) REFERENCES exchange.client(id_client) ON DELETE CASCADE;

ALTER TABLE exchange.taux_change
    ADD CONSTRAINT fk_taux_source
    FOREIGN KEY (id_devise_source) REFERENCES exchange.devise(id_devise) ON DELETE CASCADE;

ALTER TABLE exchange.taux_change
    ADD CONSTRAINT fk_taux_cible
    FOREIGN KEY (id_devise_cible) REFERENCES exchange.devise(id_devise) ON DELETE CASCADE;

ALTER TABLE exchange.transaction
    ADD CONSTRAINT fk_transaction_client
    FOREIGN KEY (id_client) REFERENCES exchange.client(id_client);

ALTER TABLE exchange.transaction
    ADD CONSTRAINT fk_transaction_source
    FOREIGN KEY (id_devise_source) REFERENCES exchange.devise(id_devise);

ALTER TABLE exchange.transaction
    ADD CONSTRAINT fk_transaction_cible
    FOREIGN KEY (id_devise_cible) REFERENCES exchange.devise(id_devise);

ALTER TABLE exchange.transaction
    ADD CONSTRAINT fk_transaction_taux
    FOREIGN KEY (id_taux) REFERENCES exchange.taux_change(id_taux);

ALTER TABLE exchange.paiement
    ADD CONSTRAINT fk_paiement_transaction
    FOREIGN KEY (id_transaction) REFERENCES exchange.transaction(id_transaction) ON DELETE CASCADE;

ALTER TABLE exchange.paiement
    ADD CONSTRAINT fk_paiement_mode
    FOREIGN KEY (id_mode_paiement) REFERENCES exchange.mode_paiement(id_mode_paiement);

ALTER TABLE exchange.paiement
    ADD CONSTRAINT fk_paiement_prestataire
    FOREIGN KEY (id_prestataire) REFERENCES exchange.prestataire_paiement(id_prestataire);

ALTER TABLE exchange.historique_transaction
    ADD CONSTRAINT fk_historique_transaction
    FOREIGN KEY (id_transaction) REFERENCES exchange.transaction(id_transaction) ON DELETE CASCADE;

CREATE INDEX idx_client_email ON exchange.client(email);
CREATE INDEX idx_paiement_transaction ON exchange.paiement(id_transaction);
CREATE INDEX idx_taux_devise_source_cible ON exchange.taux_change(id_devise_source, id_devise_cible);
CREATE INDEX idx_transaction_client ON exchange.transaction(id_client);
CREATE INDEX idx_transaction_date ON exchange.transaction(date_transaction);
CREATE INDEX idx_transaction_devises ON exchange.transaction(id_devise_source, id_devise_cible);