CREATE USER etudiant WITH PASSWORD '1234';

GRANT CONNECT ON DATABASE ecole TO etudiant;
GRANT USAGE ON SCHEMA public TO etudiant;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO etudiant;
