CREATE USER etudiant WITH PASSWORD '1234';
CREATE USER admin WITH PASSWORD 'admin123';

GRANT CONNECT ON DATABASE cours TO etudiant, admin;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO etudiant;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO admin;