DROP TABLE IF EXISTS INSCRIPTION CASCADE;
DROP TABLE IF EXISTS COURS CASCADE;
DROP TABLE IF EXISTS ETUDIANT CASCADE;

CREATE TABLE ETUDIANT (
    id_etudiant SERIAL PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE COURS (
    id_cours SERIAL PRIMARY KEY,
    titre VARCHAR(255) NOT NULL
);

CREATE TABLE INSCRIPTION (
    id_inscription SERIAL PRIMARY KEY,
    id_etudiant INT REFERENCES ETUDIANT(id_etudiant),
    id_cours INT REFERENCES COURS(id_cours)
);