name: Participations

on: [push]

jobs:
  presence:
    name: presence de fichiers pour la participation
    runs-on: ubuntu-latest
    # If container isolation is needed
    # container:
    #   image: mcr.microsoft.com/powershell

    steps:
      - uses: actions/checkout@v1

      - name: Use jq
        run: echo '{"name":"GitHub"}' | jq '.name'

      - name: Use PowerShell
        run: pwsh --version
    
      - shell: bash
        run: |
          ##
          ## Evaluating chapter 0.PlanDeCours
          ## 
          echo "Evaluating chapter 0.PlanDeCours Participation"
          cd 0.PlanDeCours
          bash .scripts/run.sh
          cd ..
          ##
          ## Evaluating chapter P.Programmation
          ## 
          echo "Evaluating chapter P.Programmation Participation"
          cd P.Programmation/1.IDE
          bash .scripts/run.sh
          cd ../2.Jupyter
          bash .scripts/run.sh
          cd ../..
          ##
          ## Evaluating chapter 1.Domaines
          ## 
          echo "Evaluating chapter 1.Domaines Participation"
          cd 1.Domaines
          pwsh .scripts/run.ps1
          cd ..
          ##
          ## Evaluating chapter 2.MySQL
          ## 
          echo "Evaluating chapter 2.MySQL Participation"
          cd 2.MySQL
          bash .scripts/run.sh
          cd ..
          ##
          ## Evaluating chapter 3.Postgres
          ## 
          echo "Evaluating chapter 3.Postgres Participation"
          cd 3.Postgres
          bash .scripts/run.sh
          cd ..
          ##
          ## Evaluating chapter 4.DCL
          ## 
          echo "Evaluating chapter 4.DCL Participation"
          cd 4.DCL
          bash .scripts/run.sh
          cd ..
          ##
          ## Evaluating chapter 5.ModelisationSQL
          ## 
          echo "Evaluating chapter 5.ModelisationSQL Participation"
          cd 5.ModelisationSQL
          pwsh .scripts/run.ps1
          cd ..
          ##
          ## Evaluating chapter 6.BATCH
          ## 
          echo "Evaluating chapter 6.BATCH Participation"
          cd 6.BATCH
          pwsh .scripts/run.ps1
          cd ..
          ##
          ## Evaluating chapter 7.PLSQL
          ## 
          echo "Evaluating chapter 7.PLSQL Participation"
          cd 7.PLSQL
          pwsh .scripts/run.ps1
          cd ..

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Vérification de la participation" -a
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
